version: '3.8'
services:
  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 8832
      POSTGRES_DB: fashion_db
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: fashion_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 8832
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
